# Normalized and expanded sound mapping
sound_mapping = {
    'Airplane': ['airplane', 'jet', 'plane', 'aircraft'],
    'Alarm': ['alarm', 'siren', 'alert'],
    'Beep/Bleep': ['beep', 'bleep', 'blip'],
    'Bell': ['bell', 'chime', 'ding'],
    'Bicycle': ['bicycle', 'bike', 'pedal'],
    'Bird Chirp': ['chirp', 'tweet', 'birdsong', 'bird call', 'singing bird', 'bird', 'forest'],
    'Bus': ['bus', 'coach', 'public transport', 'transit', 'shuttle', 'omnibus', 'motorcoach', 'city bus'],
    'Car': ['car', 'auto', 'vehicle'],
    'Cat Meow': ['meow', 'mew', 'cat sound', 'cat'],
    'Chainsaw': ['chainsaw', 'sawing'],
    'Clapping': ['clap', 'applause'],
    'Cough': ['cough', 'hack', 'throat clear'],
    'Cow Moo': ['moo', 'cow sound', 'cow', 'farm'],
    'Cowbell': ['cowbell'],
    'Crying': ['cry', 'sob', 'wail', 'baby'],
    'Dog Bark': ['bark', 'woof', 'arf', 'dog sound', 'dog'],
    'Doorbell': ['doorbell', 'chime'],
    'Drip': ['drip', 'droplet', 'dripping', 'water', 'faucet', 'leak', 'sink'],
    'Drums': ['drum', 'drumming', 'bongo'],
    'Fire': ['fire', 'crackle', 'burning'],
    'Footsteps': ['footstep', 'walking', 'steps', 'stairs'],
    'Guitar': ['guitar', 'strumming', 'plucking'],
    'Hammer': ['hammer', 'hammering'],
    'Helicopter': ['helicopter', 'chopper'],
    'Hiccup': ['hiccup', 'hiccough'],
    'Horn Honk': ['honk', 'horn blast', 'car horn', 'truck horn', 'klaxon', 'horn', 'traffic'],
    'Horse Neigh': ['neigh', 'whinny', 'horse'],
    'Insect Buzz': ['buzz', 'insect sound', 'insect', 'bug', 'fly'],
    'Jackhammer': ['jackhammer', 'pneumatic drill'],
    'Laughter': ['laugh', 'laughing', 'giggle', 'chuckle', 'ha ha'],
    'Lawn Mower': [
        'lawn mower', 'mower', 'grass cutter', 'lawncare', 'yard machine', 'tractor', 'riding mower',
        'lawn tractor', 'grass trimmer', 'yard equipment', 'landscaping equipment',
        'mower engine', 'mowing machine', 'lawn maintenance', 'outdoor power equipment'
    ],
    'Motorcycle': ['motorcycle', 'bike', 'motorbike', 'engine'],
    'Piano': ['piano', 'keys', 'keyboard'],
    'Pig Oink': ['oink', 'snort', 'pig'],
    'Power Drill': ['power drill', 'drilling', 'tool'],
    'Power Saw': ['power saw', 'saw', 'cutting', 'tool', 'wood'],
    'Rain': ['rain', 'raindrop', 'storm', 'weather'],
    'Rooster Crow': ['rooster', 'cock-a-doodle-doo'],
    'Saxophone': ['saxophone', 'sax'],
    'Sewing Machine': ['sewing machine'],
    'Sheep/Goat Bleat': ['bleat', 'baa', 'sheep', 'goat', 'animal', 'farm'],
    'Ship/Boat': ['ship', 'boat', 'vessel', 'watercraft'],
    'Shout': ['shout', 'yell', 'scream', 'voice'],
    'Singing': ['sing', 'song', 'melody'],
    'Siren': ['siren', 'wailing'],
    'Sneeze': ['sneeze', 'achoo', 'sniffle'],
    'Snoring': ['snore', 'snoring'],
    'Speech': ['talking', 'conversation', 'voice', 'dialogue', 'speaking'],
    'Stream/River': ['stream', 'brook', 'creek', 'running water', 'river', 'nature'],
    'Thunder': ['thunder', 'rumble'],
    'Train': ['train', 'locomotive'],
    'Truck': ['truck', 'lorry', 'semi', '18-wheeler', 'big rig', 'haulage', 'rig', 'articulated lorry', 'hGV', 'freight truck'],
    'Trumpet': ['trumpet', 'horn', 'brass', 'fanfare', 'bugle', 'orchestra', 'band', 'music', 'brass section', 'jazz'],
    'Vacuum Cleaner': ['vacuum', 'hoover'],
    'Violin': ['violin', 'fiddle', 'string instrument', 'bowed instrument', 'orchestra', 'strings', 'music', 'bow', 'solo', 'concerto'],
    'Washing Machine': ['washing machine', 'washer', 'spin'],
    'Waves': ['wave', 'ocean wave', 'sea', 'beach'],
    'Wind': ['wind', 'breeze', 'gust']
}

# Context word associations
context_words = {
    'Beep/Bleep': ['electronic', 'device', 'signal', 'alert', 'digital'],
    'Bird Chirp': ['forest'],
    'Bus': ['transport', 'public', 'route', 'station', 'commute', 'highway', 'city', 'urban', 'passenger', 'stop'],
    'Cow Moo': ['farm'],
    'Crying': ['baby'],
    'Drip': ['water', 'faucet', 'leak', 'sink'],
    'Footsteps': ['stairs'],
    'Horn Honk': ['traffic'],
    'Insect Buzz': ['bug', 'fly'],
    'Lawn Mower': [
        'yard', 'grass', 'lawn', 'cutting', 'outdoors', 'gardening', 'landscaping',
        'residential', 'property', 'maintenance', 'backyard', 'garden', 'hedge',
        'foliage', 'summer', 'weekend', 'homeowner'
    ],
    'Motorcycle': ['engine'],
    'Pig Oink': ['farm'],
    'Power Drill': ['tool'],
    'Power Saw': ['cutting', 'tool', 'wood'],
    'Rain': ['weather'],
    'Sheep/Goat Bleat': ['farm', 'animal'],
    'Shout': ['voice'],
    'Stream/River': ['nature'],
    'Washing Machine': ['spin'],
    'Waves': ['beach'],
    'Truck': ['highway', 'engine', 'diesel', 'freight', 'delivery', 'road', 'cargo', 'transport', 'logistics', 'shipping'],
    'Trumpet': ['orchestra', 'band', 'music', 'brass section', 'jazz'],
    'Violin': ['orchestra', 'strings', 'music', 'bow', 'solo', 'concerto']
}

# Label-to-category mapping
label_to_category = {
    'beep': 'Beep/Bleep',
    'bleep': 'Beep/Bleep',
    'blip': 'Beep/Bleep',
    'bird': 'Bird Chirp',
    'bird chirp': 'Bird Chirp',
    'cat': 'Cat Meow',
    'cat meow': 'Cat Meow',
    'cow': 'Cow Moo',
    'cow moo': 'Cow Moo',
    'dog': 'Dog Bark',
    'dog bark': 'Dog Bark',
    'horn': 'Horn Honk',
    'horn honk': 'Horn Honk',
    'horse': 'Horse Neigh',
    'horse neigh': 'Horse Neigh',
    'insect': 'Insect Buzz',
    'insect buzz': 'Insect Buzz',
    'pig': 'Pig Oink',
    'pig oink': 'Pig Oink',
    'sheep': 'Sheep/Goat Bleat',
    'goat': 'Sheep/Goat Bleat',
    'sheep/goat bleat': 'Sheep/Goat Bleat',
    'ship': 'Ship/Boat',
    'boat': 'Ship/Boat',
    'ship/boat': 'Ship/Boat',
    'stream': 'Stream/River',
    'river': 'Stream/River',
    'stream/river': 'Stream/River',
    'vacuum': 'Vacuum Cleaner',
    'vacuum cleaner': 'Vacuum Cleaner',
    'public transport': 'Bus',
    'transit': 'Bus',
    'omnibus': 'Bus',
    'motorcoach': 'Bus',
    'semi': 'Truck',
    'freight truck': 'Truck',
    '18-wheeler': 'Truck',
    'hGV': 'Truck',
    'brass': 'Trumpet',
    'string instrument': 'Violin',
    'bowed instrument': 'Violin',
    'grass cutter': 'Lawn Mower',
    'riding mower': 'Lawn Mower',
    'tractor': 'Lawn Mower',
}